Repository andela/storm-backend, pull requests merged in 2019-09, with the labels that each got.

#31 #167727737 Allow super-admin to change user role
  .sequelizerc
  package.json
  src/controllers/userController.js
  src/database/migrations/20190813040158-create-role.js
  src/database/migrations/20190815205048-create-user.js
  src/database/seeders/20190801105352-role.js
  src/database/seeders/20190819153902-user.js
  src/database/seeders/20190826210429-demo-requests.js
  src/middlewares/authorizer.js
  src/models/role.js
  src/models/user.js
  src/routes/api/user.js
  src/test/mockData/index.js
  src/test/mockData/roleMock.js
  src/test/routes/user.spec.js
  src/utils/messages.js
  src/utils/roles.js
  src/utils/templates/roleEmailMessage.js
  src/validation/userSchema.js
Labels: Finished, Review me

#39 #168233662 Modify create request controller
  src/controllers/requestController.js
  src/test/routes/request.spec.js
Labels: Review me

#34 #167727728 integrate facebook and google login
  .env-sample
  .gitignore
  package.json
  src/config/passport.js
  src/controllers/emailVerificationController.js
  src/controllers/userController.js
  src/database/migrations/20190815205048-create-user.js
  src/index.js
  src/models/user.js
  src/routes/api/auth.js
  src/routes/index.js
  src/test/mockData/mockProfile.js
  src/test/mockData/mockStrategy.js
  src/test/routes/auth.spec.js
  src/test/routes/notification.spec.js
  src/test/routes/request.spec.js
  src/test/routes/user.spec.js
  src/test/routes/verifyemail.spec.js
  src/test/testHelpers/config.js
Labels: Review me

#33 #167727738 manager reject a trip request
  .sequelizerc
  src/controllers/requestController.js
  src/database/migrations/20190815205048-create-user.js
  src/database/migrations/20190820173619-create-request.js
  src/database/seeders/20190819153902-user.js
  src/database/seeders/20190826210429-demo-requests.js
  src/middlewares/requestMiddlewares.js
  src/models/request.js
  src/routes/api/request.js
  src/services/dbServices.js
  src/test/middlewares/requestMiddlewares.spec.js
  src/test/mockData/requestMock.js
  src/test/mockData/userMock.js
  src/test/routes/request.spec.js
  src/utils/messages.js
  src/validation/requestSchema.js
Labels: Finished, Review me, WIP

#42 #167727760 Users should be able to chat on Barefoot Nomad
  src/controllers/chatController.js
  src/database/migrations/20190902172851-chat.js
  src/models/chat.js
  src/routes/api/chat.js
  src/routes/index.js
  src/services/chatServices.js
  src/services/dbServices.js
  src/test/mockData/chatMock.js
  src/test/mockData/index.js
  src/test/routes/chat.spec.js
  src/utils/messages.js
  src/validation/chatSchema.js
Labels: Review me

#38 #167727749 Travel admin can create accommodation
  .env-sample
  package.json
  src/config/cloudinaryConfig.js
  src/controllers/accommodationController.js
  src/database/migrations/20190831223315-create-accommodation.js
  src/database/seeders/20190902212248-demo-accommodation.js
  src/index.js
  src/middlewares/multer.js
  src/models/accommodation.js
  src/routes/api/accommodation.js
  src/routes/index.js
  src/test/mockData/accommodationMock.js
  src/test/routes/accommodation.spec..js
  src/utils/cloudinaryStorage.js
  src/utils/countryList.js
  src/utils/messages.js
  src/validation/JoiValidator.js
  src/validation/accommodationSchema.js
Labels: Finished, Review me

#43 #168282660 manager accept trip request
  src/controllers/requestController.js
  src/routes/api/request.js
  src/utils/messages.js
Labels: Finished, Review me

#46 #167727742 Implement approve & reject request notification
  .eslintrc
  README.md
  app.json
  src/controllers/requestController.js
  src/middlewares/requestMiddlewares.js
  src/services/notificationServices.js
  src/services/requestServices.js
  src/utils/notifications.js
Labels: Review me

#37 #167727739 Avail requests for approval
  src/controllers/requestController.js
  src/controllers/userController.js
  src/database/migrations/20190820173619-create-request.js
  src/database/seeders/20190819153902-user.js
  src/database/seeders/20190826210429-demo-requests.js
  src/middlewares/authorizer.js
  src/middlewares/requestMiddlewares.js
  src/middlewares/userMiddlewares.js
  src/models/request.js
  src/routes/api/request.js
  src/routes/api/user.js
  src/test/mockData/requestMock.js
  src/test/mockData/userMock.js
  src/test/routes/notification.spec.js
  src/test/routes/request.spec.js
  src/test/routes/user.spec.js
  src/utils/authHelper.js
  src/utils/messages.js
  src/utils/pagination.js
  src/validation/requestSchema.js
  src/validation/userSchema.js
Labels: Finished, Review me

#47 #167727759 users or managers should see most traveled destinations
  src/controllers/mostDestinationController.js
  src/controllers/requestController.js
  src/database/migrations/20190904175236-create-most-destination.js
  src/models/mostdestination.js
  src/routes/api/mostdestination.js
  src/routes/index.js
  src/services/mostDestinationServices.js
  src/test/mockData/requestMock.js
  src/test/routes/mostdestination.spec.js
Labels: Review me

#48 #167727754 implement accommodation booking
  src/controllers/accommodationController.js
  src/database/migrations/20190905112508-create-book-accomodation.js
  src/index.js
  src/models/bookaccomodation.js
  src/routes/api/accommodation.js
  src/routes/api/request.js
  src/routes/index.js
  src/test/mockData/accommodationMock.js
  src/test/routes/accommodation.spec..js
  src/utils/messages.js
  src/validation/JoiValidator.js
  src/validation/accommodationSchema.js
  src/validation/requestSchema.js
Labels: Finished, Review me

#45 #167727740 Allow users to post and get comments on a request
  src/controllers/commentController.js
  src/database/migrations/20190902185417-create-comment.js
  src/database/seeders/20190819153902-user.js
  src/database/seeders/20190826210429-demo-requests.js
  src/database/seeders/20190903163319-comment.js
  src/middlewares/authorizer.js
  src/middlewares/requestMiddlewares.js
  src/models/comment.js
  src/routes/api/comment.js
  src/routes/api/request.js
  src/routes/index.js
  src/test/mockData/commentMock.js
  src/test/mockData/index.js
  src/test/routes/comment.spec.js
  src/utils/messages.js
  src/validation/commentSchema.js
Labels: Finished, Review me

#30 #167727729 User should be able to reset Password
  src/controllers/userController.js
  src/models/user.js
  src/routes/api/user.js
  src/test/middlewares/requestMiddlewares.spec.js
  src/test/mockData/mockStrategy.js
  src/test/routes/accommodation.spec..js
  src/test/routes/auth.spec.js
  src/test/routes/chat.spec.js
  src/test/routes/notification.spec.js
  src/test/routes/request.spec.js
  src/test/routes/resetPassword.spec.js
  src/test/routes/user.spec.js
  src/test/routes/verifyemail.spec.js
  src/utils/authHelper.js
  src/utils/messages.js
  src/utils/templates/resetPasswordMessage.js
  src/validation/userSchema.js
Labels: Review me

#52 #167727750 manager re-confirm travel request
  src/middlewares/confirmationMiddleware.js
  src/routes/api/request.js
  src/test/routes/mostdestination.spec.js
  src/test/routes/request.spec.js
  src/utils/messages.js
Labels: Review me

#51 #167727753 Pre-screened accommodation supplier can add accommodation
  src/controllers/accommodationController.js
  src/database/migrations/20190813040158-create-role.js
  src/database/migrations/20190831223315-create-accommodation.js
  src/database/seeders/20190801105352-role.js
  src/database/seeders/20190819153902-user.js
  src/database/seeders/20190902212248-demo-accommodation.js
  src/models/accommodation.js
  src/routes/api/accommodation.js
  src/test/mockData/accommodationMock.js
  src/test/routes/accommodation.spec..js
  src/utils/cloudinaryStorage.js
  src/utils/messages.js
  src/utils/roles.js
  src/validation/accommodationSchema.js
Labels: Finished, Heroku Verified, Review me

#49 #168335247 default image for creating accommodation
  src/database/migrations/20190831223315-create-accommodation.js
  src/models/accommodation.js
Labels: Finished, Review me

#56 setup morgan for logging
  package.json
  src/index.js
Labels: Finished, Heroku Verified, Review me

#50 #168336500 Fix Redis Connection failure in Docker
  docker-compose.yml
  heroku.yml
  src/controllers/userController.js
  src/middlewares/blacklistMiddleware.js
  src/test/mockData/requestMock.js
Labels: Review me

#60 #168412842 Logout Functionality re-factoring using PostgreSQL DB
  app.json
  docker-compose.yml
  heroku.yml
  package.json
  src/config/redis.js
  src/controllers/userController.js
  src/database/migrations/20190910180853-create-token-blacklist.js
  src/middlewares/blacklistMiddleware.js
  src/models/tokenblacklist.js
  src/routes/api/comment.js
  src/routes/api/user.js
Labels: Heroku Verified, Review me

#54 #167727748 Allow users to receive notifications for posted comments
  src/config/swaggerDoc.js
  src/controllers/commentController.js
  src/database/migrations/20190826163252-create-notification.js
  src/middlewares/requestMiddlewares.js
  src/middlewares/userMiddlewares.js
  src/models/notification.js
  src/services/notificationServices.js
  src/test/routes/comment.spec.js
  src/utils/notificationTypes.js
  src/utils/notifications.js
Labels: Finished, Heroku Verified, Review me

#53 #167727746 user edit request
  src/controllers/requestController.js
  src/database/migrations/20190825084258-sub-request.js
  src/database/seeders/20190819153902-user.js
  src/database/seeders/20190826210429-demo-requests.js
  src/database/seeders/20190908153338-subrequest.js
  src/index.js
  src/middlewares/requestMiddlewares.js
  src/models/request.js
  src/routes/api/request.js
  src/test/middlewares/requestMiddlewares.spec.js
  src/test/mockData/requestMock.js
  src/test/mockData/userMock.js
  src/test/routes/request.spec.js
  src/validation/requestSchema.js
Labels: Finished, Heroku Verified, Review me

#57 #167727743 user should be able to delete comments they made
  src/controllers/commentController.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20190902185417-create-comment.js
  src/database/seeders/20190903163319-comment.js
  src/index.js
  src/models/comment.js
  src/routes/api/comment.js
  src/routes/api/request.js
  src/test/mockData/commentMock.js
  src/test/routes/comment.spec.js
  src/utils/messages.js
Labels: Review me

#55 #167727755 Like/unlike an accommodation
  src/controllers/accommodationController.js
  src/database/migrations/20190907143807-create-accommodation-likes.js
  src/middlewares/accommodationMiddlewares.js
  src/models/accommodationLike.js
  src/routes/api/accommodation.js
  src/routes/api/chat.js
  src/routes/api/comment.js
  src/routes/api/mostdestination.js
  src/routes/api/notification.js
  src/routes/api/request.js
  src/routes/api/user.js
  src/services/dbServices.js
  src/test/mockData/accommodationMock.js
  src/test/routes/accommodation.spec.js
  src/validation/accommodationSchema.js
Labels: Finished, Review me

#59 #167727756 enable user to provide feedback on accommodation facility
  .travis.yml
  README.md
  src/controllers/accommodationController.js
  src/database/migrations/20190910184108-create-feedback-accomodation.js
  src/models/accomodationfeedback.js
  src/routes/api/accommodation.js
  src/routes/index.js
  src/test/mockData/accommodationMock.js
  src/test/routes/accommodation.spec.js
  src/utils/messages.js
  src/validation/accommodationSchema.js
Labels: Heroku Verified, Review me

#63 #167727758 Implement stats of trips made by user
  package.json
  src/controllers/userTripStatsController.js
  src/database/seeders/20190826210429-demo-requests.js
  src/routes/api/tripStats.js
  src/routes/index.js
  src/test/routes/request.spec.js
  src/validation/requestSchema.js
Labels: Finished, Heroku Verified, Review me

#68 #168432541 create and get office location
  src/controllers/officeLocationController.js
  src/database/migrations/20190913121008-create-office-locations.js
  src/database/seeders/20190914074114-demo-office-location.js
  src/models/officelocation.js
  src/routes/api/officeLocation.js
  src/routes/index.js
  src/test/mockData/index.js
  src/test/mockData/officelocationMock.js
  src/test/routes/officelocation.spec.js
  src/utils/messages.js
  src/validation/officeLocationSchema.js
Labels: Heroku Verified, Review me

#70 #167727757 Implement accommodation rating
  .babelrc
  README.md
  package.json
  src/controllers/accommodationController.js
  src/database/migrations/20190914085520-create-rating.js
  src/database/seeders/20190819153902-user.js
  src/middlewares/accommodationMiddlewares.js
  src/models/accommodation.js
  src/models/rating.js
  src/routes/api/accommodation.js
  src/services/ratingService.js
  src/services/userServices.js
  src/test/mockData/accommodationMock.js
  src/test/routes/accommodation.spec.js
  src/validation/accommodationSchema.js
Labels: Heroku Verified, Review me

#71 #168405336 Allow users to update their profile image
  .env-sample
  package.json
  src/config/cloudinaryConfig.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/migrations/20190815205048-create-user.js
  src/middlewares/imageUploader.js
  src/middlewares/multer.js
  src/models/user.js
  src/routes/api/user.js
  src/test/middlewares/imageUploader.spec.js
  src/test/mockData/cloudinaryMock.js
  src/test/mockData/fileMock.js
  src/test/mockData/index.js
  src/test/routes/user.spec.js
  src/test/testHelpers/config.js
  src/utils/cloudinaryStorage.js
  src/utils/messages.js
  testImages/test.png
Labels: Finished, Heroku Verified, Review me
