Repository andela/storm-backend, pull requests merged in 2019-08, with the labels that each got.

#1 #167727715 Updated readme with Houndci badge
  .hound.yml
  README.md
Labels: Finished

#2 #167889367 Refactor existing code base
  .babelrc
  .gitignore
  package.json
  src/config/index.js
  src/config/passport.js
  src/controllers/.gitkeep
  src/database/.gitkeep
  src/index.js
  src/middlewares/.gitkeep
  src/models/User.js
  src/routes/api/index.js
  src/routes/api/users.js
  src/routes/index.js
  src/services/.gitkeep
  src/utils/messages.js
  src/utils/response.js
  src/validation/.gitkeep
Labels: Finished, Review me

#4 #167727719 Setup dotenv
  .gitignore
  package.json
  src/config/env.js
  src/index.js
Labels: Review me

#3 #167727714 Configure Eslint
  .eslintignore
  .eslintrc.json
  .hound.yml
  package.json
  src/index.js
  src/utils/messages.js
  src/utils/response.js
Labels: Review me

#5 #166645992 setup docker for backend
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: Finished, Review me

#9 #167727718 setup unit test
  .eslintrc.json
  .gitignore
  package.json
  src/index.js
  src/test/index.spec.js
  src/test/testHelpers/config.js
Labels: Review me

#8 #167941066 update readme with codeclimate maintainability badge
  README.md
Labels: Review me

#7 #167727713 Setup Sequelize
  .env-sample
  .sequelizerc
  README.md
  package.json
  src/database/config/config.js
  src/database/migrations/20190815205048-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/.gitkeep
Labels: Review me

#10 #167727717 Integrates TravisCI
  .travis.yml
  README.md
Labels: Review me

#11 #167727720 Integrate Coveralls code coverage service
  README.md
Labels: Review me

#12 #167727721 Setup api documentation
  package.json
  src/config/swaggerDoc.js
  src/index.js
  src/routes/index.js
  src/test/routes/index.spec.js
  src/utils/messages.js
Labels: Finished, Review me

#13 #167941118 Setup husky
  package.json
Labels: Finished, Review me

#14 #167727724 allow a user to create an account
  .env-sample
  .travis.yml
  package.json
  src/config/env.js
  src/config/swaggerDoc.js
  src/controllers/.gitkeep
  src/controllers/userController.js
  src/database/migrations/20190815205048-create-user.js
  src/database/models/user.js
  src/database/seeders/20190819153902-user.js
  src/index.js
  src/models/User.js
  src/routes/api/index.js
  src/routes/api/user.js
  src/routes/api/users.js
  src/routes/index.js
  src/services/.gitkeep
  src/services/dbServices.js
  src/test/mockData/index.js
  src/test/mockData/userMock.js
  src/test/routes/auth.spec.js
  src/utils/authHelper.js
Labels: Review me, WIP

#16 #167727727 Implement email & password authentication
  package.json
  src/controllers/userController.js
  src/routes/api/user.js
  src/services/userServices.js
  src/test/routes/auth.spec.js
  src/test/testHelpers/config.js
  src/utils/messages.js
Labels: Review me

#18 #167727730 Logout Functionality
  .eslintrc.json
  .travis.yml
  package.json
  src/controllers/userController.js
  src/middlewares/blacklistMiddleware.js
  src/routes/api/user.js
  src/test/middlewares/validator.spec.js
  src/test/routes/auth.spec.js
  src/test/testHelpers/config.js
  src/utils/messages.js
Labels: Review me

#22 #168055189 Fix duplicate email error in signup route
  src/controllers/userController.js
  src/services/userServices.js
  src/test/mockData/userMock.js
  src/test/routes/auth.spec.js
  src/utils/messages.js
Labels: Review me

#20 #167727732 One way trip request
  .gitignore
  README.md
  package.json
  src/config/index.js
  src/config/passport.js
  src/controllers/requestController.js
  src/database/config/config.js
  src/database/migrations/20190820173619-create-request.js
  src/database/models/request.js
  src/index.js
  src/middlewares/userMiddlewares.js
  src/routes/api/request.js
  src/routes/api/user.js
  src/routes/index.js
  src/services/dbServices.js
  src/test/mockData/index.js
  src/test/mockData/requestMock.js
  src/test/mockData/userMock.js
  src/test/routes/request.spec.js
  src/test/testHelpers/config.js
  src/utils/messages.js
  src/validation/JoiValidator.js
  src/validation/requestSchema.js
Labels: Finished, Review me

#21 #168058148 setup database configs for docker
  .env-sample
  .gitignore
  Dockerfile
  docker-compose.yml
  entrypoint.sh
Labels: Review me

#19 #167727725 send email verification on signup
  .env-sample
  package.json
  src/config/verifyEmailMessage.js
  src/controllers/emailVerificationController.js
  src/controllers/userController.js
  src/database/migrations/20190815205048-create-user.js
  src/database/models/user.js
  src/database/seeders/.gitkeep
  src/database/seeders/20190819153902-user.js
  src/routes/api/user.js
  src/routes/index.js
  src/test/routes/verifyemail.spec.js
  src/utils/createTemplate.js
  src/utils/sendMail.js
Labels: Review me, WIP

#17 #167727731 Get and update user details
  .gitignore
  src/controllers/userController.js
  src/database/migrations/20190815205048-create-user.js
  src/database/models/user.js
  src/middlewares/userMiddlewares.js
  src/routes/api/request.js
  src/routes/api/user.js
  src/services/dbServices.js
  src/test/mockData/userMock.js
  src/test/routes/user.spec.js
  src/utils/authHelper.js
  src/utils/messages.js
  src/validation/JoiValidator.js
  src/validation/userSchema.js
Labels: Finished, Review me

#25 #167727733 Return trip request
  src/controllers/requestController.js
  src/database/migrations/20190820173619-create-request.js
  src/models/request.js
  src/routes/api/request.js
  src/test/mockData/requestMock.js
  src/test/routes/request.spec.js
  src/validation/requestSchema.js
Labels: Review me

#29 #167727736: User should get his requests
  src/controllers/requestController.js
  src/database/seeders/20190819153902-user.js
  src/database/seeders/20190826210429-demo-requests.js
  src/middlewares/userMiddlewares.js
  src/routes/api/request.js
  src/routes/api/user.js
  src/services/dbServices.js
  src/test/routes/request.spec.js
  src/test/routes/user.spec.js
  src/test/routes/verifyemail.spec.js
  src/utils/messages.js
  src/utils/pagination.js
  src/validation/JoiValidator.js
  src/validation/requestSchema.js
  src/validation/userSchema.js
Labels: Finished, Review me

#36 #168190060 Chore(seeds): hash passwords in seed files
  package.json
  src/database/seeders/20190819153902-user.js
  src/models/user.js
  src/utils/authHelper.js
Labels: Finished, Review me, chore

#26 #167727744 implement search functionality
  src/controllers/requestController.js
  src/routes/api/request.js
  src/services/requestServices.js
  src/test/mockData/userMock.js
  src/test/routes/request.spec.js
  src/utils/messages.js
  src/validation/JoiValidator.js
  src/validation/requestSchema.js
Labels: Finished

#35 #168190297 Integrate redis server on heroku app and docker
  .env-sample
  docker-compose.yml
  src/config/redis.js
  src/controllers/userController.js
  src/middlewares/blacklistMiddleware.js
Labels: Review me

#32 #167727735 Implement new travel request notification
  .env-sample
  .travis.yml
  package.json
  src/config/pusher.js
  src/controllers/emailVerificationController.js
  src/controllers/notificationController.js
  src/controllers/requestController.js
  src/controllers/userController.js
  src/database/migrations/20190815205048-create-user.js
  src/database/migrations/20190826163252-create-notification.js
  src/database/seeders/20190819153902-user.js
  src/models/notification.js
  src/models/user.js
  src/routes/api/notification.js
  src/routes/index.js
  src/services/notificationServices.js
  src/services/userServices.js
  src/test/mockData/requestMock.js
  src/test/mockData/userMock.js
  src/test/routes/notification.spec.js
  src/test/routes/request.spec.js
  src/test/routes/user.spec.js
  src/test/routes/verifyemail.spec.js
  src/test/testHelpers/config.js
  src/utils/createEmailTemplate.js
  src/utils/notifications.js
  src/utils/templates/verifyEmailMessage.js
Labels: Review me
